name: "K8s Codegen Check"

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
    paths:
      - "pkg/apis/**"
      - "pkg/aggregator/apis/**"
      - "pkg/apimachinery/apis/**"
      - "hack/**"
      - "apps/**"
      - "*.sum"

jobs:
  check:
    name: K8s Codegen Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5
      with:
        persist-credentials: false

    - name: Set go version
      uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c
      with:
        go-version-file: go.mod

    - name: Update k8s codegen
      run: ./hack/update-codegen.sh

    - name: Check for k8s codegen changes
      run: |
        if ! git diff --exit-code --quiet; then
          echo "Changes detected:"
          git diff
          echo "Please run './hack/update-codegen.sh' and commit the changes."
          exit 1
        fi
